# Generated by Django 4.2.11 on 2024-10-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_alter_usermodel_managers_usermodel_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_landlord',
            field=models.BooleanField(default=False),
        ),
    ]
