# Generated by Django 5.2.7 on 2025-10-30 16:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format:             '+234xxxxxxx'. Cannot be more that 9 digits and a maximum of 15 digits is allowed.", regex='^\\+?234?\\d{9,15}$')])),
                ('date_of_birth', models.DateField()),
                ('preferred_location', models.CharField(max_length=255)),
                ('budget_range_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_range_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lease_duration', models.CharField(choices=[('6_months', '6 Months'), ('1_year', '1 Year'), ('other', 'Other')], max_length=50)),
                ('year_of_study', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('field_of_study', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
