# Generated by Django 5.1.1 on 2024-11-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="dislike",
        ),
        migrations.RemoveField(
            model_name="review",
            name="like",
        ),
        migrations.AddField(
            model_name="review",
            name="is_liked",
            field=models.BooleanField(default="", null=True),
        ),
    ]
