# Generated by Django 5.1.1 on 2025-01-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0004_alter_review_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="is_liked",
        ),
        migrations.AddField(
            model_name="review",
            name="dislikes",
            field=models.PositiveBigIntegerField(default="", null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="likes",
            field=models.PositiveBigIntegerField(default="", null=True),
        ),
    ]
