# Generated by Django 5.1.1 on 2024-11-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('apartment_type', models.CharField(choices=[('one_room', 'One room'), ('self_con', 'Self con'), ('room_and_parlour', 'A room and parlour')], default='one_room', max_length=50)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('location', models.CharField(choices=[('ODI', 'Odim'), ('ODE', 'Odenigwe'), ('BF', 'Behind Flat'), ('GH', 'Green House'), ('HT', 'Hilltop'), ('SQ', 'Staff Quarters')], default='HT', max_length=255)),
                ('is_leased', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='')),
            ],
        ),
    ]
