# Generated by Django 5.1.1 on 2024-11-22 14:06

import apartment.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('apartment_type', models.CharField(choices=[('one_room', 'One room'), ('self_con', 'Self con'), ('room_and_parlour', 'A room and parlour')], default='one_room', max_length=50)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('location', models.CharField(choices=[('ODI', 'Odim'), ('ODE', 'Odenigwe'), ('BF', 'Behind Flat'), ('GH', 'Green House'), ('HT', 'Hilltop'), ('SQ', 'Staff Quarters')], default='HT', max_length=255)),
                ('is_leased', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apartment.models.user_directory_path)),
                ('apartments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='self_related', to='apartment.apartment')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApartmentImage',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('images', models.ImageField(upload_to=apartment.models.user_directory_path)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='apartment.apartment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
