# Generated by Django 5.1.1 on 2024-10-18 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 18, 15, 4, 10, 297435, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='apartment',
            name='is_leased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartment',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
