# Generated by Django 5.1.1 on 2024-11-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='id',
            field=models.UUIDField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='apartmentimage',
            name='id',
            field=models.UUIDField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
