# Generated by Django 5.1.1 on 2024-10-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_apartment_created_apartment_is_leased_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
