# Generated by Django 5.1.1 on 2024-11-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0003_alter_apartment_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='roommate_required',
            field=models.BooleanField(default=False),
        ),
    ]
