# Generated by Django 5.1.1 on 2024-11-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0004_apartment_roommate_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
