# Generated by Django 5.1.1 on 2024-11-10 11:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0004_alter_apartment_id_alter_apartmentimage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='apartmentimage',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
